In [1]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [18]:
import time

a = np.random.rand(10000000)
b = np.random.rand(10000000)
print(a)
print(b)
tic = time.time()
c=np.dot(a,b)
toc= time.time()
print(c)
print("Vectorize version: "+ str(1000*( toc -  tic))+ "ms")
c=0
tic=time.time()

for i in range(10000000):
    c+= a[i]* b[i]
toc = time.time()
print(c)
print("UnVectorize version: "+ str(1000*( toc -  tic))+ "ms")

[0.37491568 0.18247198 0.70069516 ... 0.74205955 0.42859559 0.74194183]
[0.39019548 0.14314189 0.33047235 ... 0.85802717 0.97519756 0.32001733]
2501039.526544598
Vectorize version: 13.133764266967773ms
2501039.5265446636
UnVectorize version: 8920.265197753906ms
